### ISSUE TITLE
Check order of parameters

### ISSUE THREAD

**Issue by AHorneffer** [revoltek/losoto#12]
When the `losoto` script is called with the wrong order of arguments (i.e. `losoto parset h5parm` instead of `losoto h5parm parset`), then one gets a rather confusing error message (see below). An error message that gives a bit more of a hint what went wrong would really be appreciated.
```
(horneffer)lhd002> losoto /data/scratch/horneffer/h5imp_cal_losoto.h5.parset /data/scratch/horneffer/h5imp_cal_losoto.h5
log4cplus:ERROR No appenders could be found for logger (LCS.Common.EXCEPTION).
log4cplus:ERROR Please initialize the log4cplus system properly.
Traceback (most recent call last):
  File "/opt/cep/losoto/current/bin/losoto", line 4, in <module>
    __import__('pkg_resources').run_script('losoto==1.0.0', 'losoto')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/cep/losoto/losoto-master-20160704/lib/python2.7/site-packages/losoto-1.0.0-py2.7.egg/EGG-INFO/scripts/losoto", line 99, in <module>
    parset = lofar.parameterset.parameterset( parsetFile )
  File "/opt/cep/lofar/lofar_versions/LOFAR-Release-2_16_4/lofar_build/install/gnu_opt/lib/python2.7/site-packages/lofar/parameterset/__init__.py", line 93, in __init__
    PyParameterSet.__init__ (self, filename, caseInsensitive);
RuntimeError: Assertion: pos != string::npos; Unbalanced quoted string at position 191 in N��A
```

**Comment by mhardcastle** [comment]
To be fair, the final error here comes from lofar.parameterset.parameterset(), which could/should be made to do some checks on whether it's been handed a plain text file, but not by losoto developers...

**Comment by mhardcastle** [comment]
Losoto could do

import mimetypes
if mimetypes.guess_type( parsetFile )[0] != 'text/plain':
    print 'sensible error message goes here'

**Comment by AHorneffer** [comment]
Well, it doesn't seem to work too well on CEP3:
```
(horneffer)lhd002> python
Python 2.7.3 (default, Feb 27 2014, 19:58:35) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mimetypes
>>> mimetypes.guess_type('/data/scratch/horneffer/h5imp_cal_losoto.h5.parset')
(None, None)
>>> mimetypes.guess_type("/data/scratch/horneffer/h5imp_cal_losoto.h5.parset")
(None, None)
>>> mimetypes.guess_type("/data/scratch/horneffer/h5imp_cal_losoto.h5")
(None, None)
>>> mimetypes.guess_type("drawMS.tgz")
('application/x-tar', 'gzip')
>>> 
```

`file` works better:
```
(horneffer)lhd002> file /data/scratch/horneffer/h5imp_cal_losoto.h5.parset /data/scratch/horneffer/h5imp_cal_losoto.h5
/data/scratch/horneffer/h5imp_cal_losoto.h5.parset: ASCII text
/data/scratch/horneffer/h5imp_cal_losoto.h5:        Hierarchical Data Format (version 5) data

```

**Comment by nudomarinero** [comment]
Then, this should work for the HDF5 file:
```
if not tables.is_hdf5_file(h5parmFile):
    print 'sensible error message goes here'
```

**Comment by AHorneffer** [comment]
In order to (also) get this fixed in the `parameterset` library, I created an issue on the LOFAR issue-tracker about this: https://support.astron.nl/lofar_issuetracker/issues/9765
