### ISSUE TITLE
Crash at FARADAY

### ISSUE THREAD

**Issue by adrabent** [revoltek/losoto#132]
Dear all,

I try to run the FARADAY module from the current `master` branch, but I get this error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/losoto", line 155, in <module>
    returncode += ops[ op ]._run_parser( soltab, parser, step )
  File "/usr/local/lib/python3.8/dist-packages/losoto/operations/faraday.py", line 19, in _run_parser
    return run(soltab, soltabOut, refAnt, maxResidual, ncpu)
  File "/usr/local/lib/python3.8/dist-packages/losoto/operations/faraday.py", line 116, in run
    tuples = [(t,coord_rr,coord_ll,wt,vl,solType,coord,maxResidual) for t,wt,vl in zip(list(np.arange(len(times))), weightsliced, valsliced)]
  File "/usr/local/lib/python3.8/dist-packages/losoto/operations/faraday.py", line 116, in <listcomp>
    tuples = [(t,coord_rr,coord_ll,wt,vl,solType,coord,maxResidual) for t,wt,vl in zip(list(np.arange(len(times))), weightsliced, valsliced)]
NameError: free variable 'coord_rr' referenced before assignment in enclosing scope
```
This is the parset I have used:

```
[FARADAY]
operation=FARADAY
soltabout=faraday
refAnt=CS002HBA1
soltab = sol000/rotation000
```
This issue **does not** occur at the latest tagged version (2.2.1), but on latest **master**.

Cheers,
Alex

**Comment by cgroeneveld** [comment]
I'll have a look!

**Comment by cgroeneveld** [comment]
@adrabent Do you have an example H5, so I can test things?

**Comment by adrabent** [comment]
You find an example h5parm [here](https://tlscloud.tls-tautenburg.de/owncloud/index.php/s/uXs2VAhjDQmRFkf).

**Comment by cgroeneveld** [comment]
#133 should solve this issue
