### ISSUE TITLE
losoto FLAGSTATION uses deprecated numpy.warnings and crashes

### ISSUE THREAD

**Issue by adrabent** [revoltek/losoto#141]
Using most recent losoto and numpy version 1.24.1 I encounter the following error in the `FLAGSTATION` step:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/losoto/lib_operations.py", line 34, in run
    self.funct(*parms, outQueue=self.outQueue)
  File "/usr/local/lib/python3.8/dist-packages/losoto/operations/flagstation.py", line 395, in _flag_bandpass
    with np.warnings.catch_warnings():
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'warnings'
```

Going back to numpy version 1.23.0 fixes the issue.

**Comment by revoltek** [comment]
@darafferty can you have a look at this?

**Comment by darafferty** [comment]
@adrabent Can you try the `fix_numpy_warnings` branch and see whether the issue is fixed? If so, I'll make a PR for it.

**Comment by darafferty** [comment]
OK, I'll make a PR for it. Thanks for testing it!
