### ISSUE TITLE
losoto clockTEC uses unsupported array type in recent numpy and crashes

### ISSUE THREAD

**Issue by adrabent** [revoltek/losoto#142]
Using most recent losoto and numpy version 1.24.1 I encounter the following error in the `_fitClockTEC.py` step:

```
Traceback (most recent call last):
  File "/usr/local/bin/losoto", line 155, in <module>
    returncode += ops[ op ]._run_parser( soltab, parser, step )
  File "/usr/local/lib/python3.8/dist-packages/losoto/operations/clocktec.py", line 28, in _run_parser
    return run(soltab, tecsoltabOut, clocksoltabOut, offsetsoltabOut, tec3rdsoltabOut, flagBadChannels, flagCut, chi2cut, combinePol, removePhaseWraps, fit3rdorder, circular, reverse, invertOffset, nproc)
  File "/usr/local/lib/python3.8/dist-packages/losoto/operations/clocktec.py", line 109, in run
    result=doFit(vals,flags==0,freqs,stations,station_positions,axes,\
  File "/usr/local/lib/python3.8/dist-packages/losoto/operations/_fitClockTEC.py", line 850, in doFit
    (offset[:, pol], wraps, steps) = correctWraps(tecarray, residualarray, freqs, station_positions)
  File "/usr/local/lib/python3.8/dist-packages/losoto/operations/_fitClockTEC.py", line 643, in correctWraps
    slope = np.ma.dot(np.linalg.inv(np.dot(lonlat, lonlat.T)), np.ma.dot(lonlat, TEC.T))
  File "<__array_function__ internals>", line 200, in inv
  File "/usr/local/lib/python3.8/dist-packages/numpy/linalg/linalg.py", line 534, in inv
    t, result_t = _commonType(a)
  File "/usr/local/lib/python3.8/dist-packages/numpy/linalg/linalg.py", line 147, in _commonType
    raise TypeError("array type %s is unsupported in linalg" %
TypeError: array type float16 is unsupported in linalg
```

This may be related with the enforcement of the newest numpy to specify the float precision.

Cheers,
Alex

**Comment by tikk3r** [comment]
I'm encountering the same issue with Numpy 1.22.4.

**Comment by gmloose** [comment]
Hm, the `np.float` issue has been resolved. But it could be that this is collateral damage. Commit `deefe6d2` is quite recent, and might be the culprit.
