### ISSUE TITLE
STRUCTURE operation fails in recent numpy and losoto version

### ISSUE THREAD

**Issue by adrabent** [revoltek/losoto#152]
Dear all,

if I try using ` losoto` with a `numpy` version later than 1.23.0 and the current [latest release](https://github.com/revoltek/losoto/releases/tag/2.4.2) of `losoto` I get the following error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/losoto", line 155, in <module>
    returncode += ops[ op ]._run_parser( soltab, parser, step )
  File "/usr/local/lib/python3.8/dist-packages/losoto/operations/structure.py", line 16, in _run_parser
    return run(soltab, doUnwrap, refAnt, plotName, ndiv)
  File "/usr/local/lib/python3.8/dist-packages/losoto/operations/structure.py", line 161, in run
    ymin = np.max(1e-9,np.min(variance[myselect]))
  File "<__array_function__ internals>", line 200, in amax
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 2820, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

I guess something seems to be still messed up with the change of using types in `numpy`.

Alex

**Comment by adrabent** [comment]
Fixed with https://github.com/revoltek/losoto/commit/75fe55dbc06c4d40c125adad77aa10efec5fda31
