### ISSUE TITLE
Not compatible with matplotlib v2.0.0

### ISSUE THREAD

**Issue by ajstewart** [revoltek/losoto#16]
I don't think this needs immediate addressing but it's worth noting, at least in the documentation, that currently losoto doesn't seem to be compatible with the newly released matplotlib 2.0.0.

Specifically it seems to be when generating plots when multithreaded:

```
DEBUG: Loading FLAG module.
DEBUG: Loading TECSCREEN module.
DEBUG: Loading CLIP module.
DEBUG: Loading TECFIT module.
WARNING: Appending to pipeline.h5parm.
INFO: --> Starting 'plotA1' step (operation: PLOT).
INFO: Plotting soltab: amplitude000
DEBUG: Spawning 12 threads...
Process multiThread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/stewart/.virtualenvs/PiLL/local/lib/python2.7/site-packages/losoto/operations_lib.py", line 35, in run
    self.funct(*parms, outQueue=self.outQueue)
  File "/home/stewart/.virtualenvs/PiLL/local/lib/python2.7/site-packages/losoto/operations/plot.py", line 23, in plot
    import matplotlib.pyplot as plt # after setting "Agg" to speed up
  File "/home/stewart/.virtualenvs/PiLL/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/home/stewart/.virtualenvs/PiLL/local/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/home/stewart/.virtualenvs/PiLL/local/lib/python2.7/site-packages/matplotlib/contour.py", line 22, in <module>
    import matplotlib.font_manager as font_manager
  File "/home/stewart/.virtualenvs/PiLL/local/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1432, in <module>
    _rebuild()
  File "/home/stewart/.virtualenvs/PiLL/local/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1421, in _rebuild
    with cbook.Locked(cachedir):
  File "/home/stewart/.virtualenvs/PiLL/local/lib/python2.7/site-packages/matplotlib/cbook.py", line 2738, in __enter__
    raise self.TimeoutError(err_str)
TimeoutError: LOCKERROR: matplotlib is trying to acquire the lock
    u'/home/stewart/.cache/matplotlib/.matplotlib_lock-*'
and has failed.  This maybe due to any other process holding this
lock.  If you are sure no other matplotlib process is running try
removing these folders and trying again.
```

Downgrading to matplotlib 1.5.2 avoids this issue.

Seems to be related to this matplotlib issue: https://github.com/matplotlib/matplotlib/issues/7776.

**Comment by revoltek** [comment]
Tested on LoSoTo 2.0 with no problem
