### ISSUE TITLE
H5parm_exporter.py crash: 'numpy.float64' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by ajstewart** [revoltek/losoto#17]
I've experienced this during the running of the PiLL pipeline, reported here: https://github.com/lofar-astron/PiLL/issues/3

When attempting to use H5parm_exporter.py to export the H5parm file 'pipeline.h5parm2' to the globaldb 'pipeline.globaldbclock' I get the below numpy error.

```
(PiLL) stewart@pi3:/cherrypi/stewart/NCP_Processing/2017-Processing/PiLL-L259185/fourth-test-L259185/pipeline$ ~/cherrypi/NCP_Processing/2017-Processing/PiLL-L259185/scripts/H5parm_exporter.py -v -c -t "amplitudeSmooth000;phaseOrig000;clock000" pipeline.h5parm2 pipeline.globaldbclock
INFO: Input H5parm filename = pipeline.h5parm2
DEBUG: Reading from pipeline.h5parm2.
INFO: Input globaldb/SB filename = pipeline.globaldbclock
INFO: Solution set name = sol000
INFO: Output globaldb/SB filename = pipeline.globaldbclock
INFO: Using solution tables: ['amplitudeSmooth000', 'phaseOrig000', 'clock000']
INFO: Found solution types in input parmdb and H5parm: Gain, Clock
INFO: Filling pipeline.globaldbclock/sol000_instrument-0:
DEBUG: Caching...                                                                                                              |
DEBUG: Caching...
DEBUG: Caching...
Traceback (most recent call last):
  File "/home/stewart/cherrypi/NCP_Processing/2017-Processing/PiLL-L259185/scripts/H5parm_exporter.py", line 552, in <module>
    val = np.tile( val, np.append([nfreq], np.ones(len(val.shape)) ) )
  File "/mnt/home/stewart/.virtualenvs/PiLL/local/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 881, in tile
    return c.reshape(shape_out)
TypeError: 'numpy.float64' object cannot be interpreted as an index
Closing remaining open files:pipeline.h5parm2...done
```

I have tried this manually and as part of the pipeline. I have also tried the 'normal' H5parm_exporter.py (i.e. not the PiLL version although it has minimal changes anyway). 

I am using numpy v1.12.0.

I attempted to switch to numpy 1.9.0 as listed in the readme however this broke the script immediately because of some other module (tables) import error, so I think that module is relying on numpy > 1.9.0. But I can try to correct this if you immediately think it's to do with the numpy version.

**Comment by ajstewart** [comment]
I was able to downgrade to numpy v1.11.0 and it now runs without this error. I cannot see any obvious changes to numpy that caused it, but currently it seems like something in numpy v1.12.0 is not compatible.
