### ISSUE TITLE
phase_offset return by clocktec fit cannot be subtracted in the "residual" step

### ISSUE THREAD

**Issue by rvweeren** [revoltek/losoto#26]
The phase_offset returned by clocktec fitting cannot be subtracted from the phases in the "residual" step. 

LoSoTo.Steps.residual.Operation = RESIDUALS
LoSoTo.Steps..residual.Soltab = [sol000/phase000]
LoSoTo.Steps..residual.Sub = [sol000/phase_offset000]

INFO: --> Working on soltab: phase000
INFO: Subtracting table: sol000/phase_offset000
Traceback (most recent call last):
File "../../rvweeren/software/losoto/bin/losoto", line 145, in <module>
logging.info <http://logging.info>("Step \'" + step + "\' completed successfully.")
File "../../rvweeren/software/losoto/bin/losoto", line 141, in <module>
  returncode = ops[ op ].run( step, parset, H )
File "/home/rvweeren/.local/lib/python2.7/site-packages/losoto/operations/residuals.py", line 99, in run
  else: sw.setValues(sf.getValues(retAxesVals=False)-sfs.getValues(retAxesVals=False))
ValueError: operands could not be broadcast together with shapes (2,1,62,125,3595) (62,)
Elapsed:32:41.37,User=2541.075,System=1292.100,CPU=195.4%.

**Comment by rvweeren** [comment]
this was a losoto 1.0 issue, no need fixing it tanymore (will re-open if the issue reappears in 2.0)
