### ISSUE TITLE
Importing killMS doesn't handle case when there are no TEC solutions

### ISSUE THREAD

**Issue by Joshuaalbert** [revoltek/losoto#51]
Hey Fra,

I'm trying to export the result of a killMS solve to hdf5 format.

The command I try,
``` bash
killMS2H5parm.py test.hdf5 P126+65BEAM_1_chan0-20.ms/killMS.DDjosh.sols.npz
```
The error,
``` python 
INFO: KILLMS filenames = P126+65BEAM_1_chan0-20.ms/killMS.DDjosh.sols.npz
INFO: H5parm filename = test.hdf5
Traceback (most recent call last):
  File "/home/albert/git/losoto/bin/killMS2H5parm.py", line 85, in <module>
    vals_tec = SolsDico['SolsTEC'].T
  File "/net/lofar1/data1/albert/miniconda3/envs/lofar27/lib/python2.7/site-packages/numpy/lib/npyio.py", line 239, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'SolsTEC is not a file in the archive'
```
## How the kMS solve was done
This is the command that created the solutions,
``` bash
kMS.py \
--MSName my.ms \
--SolverType KAFCA \
--PolMode Scalar \
--BaseImageName image_full_ampphase_di_m.NS --dt 0.133333 \
--NIterKF 6 \
--CovQ 0.1 \
--LambdaKF=0.5 \
--NCPU 60 \
--OutSolsName DDjosh \
--NChanSols 2 \
--PowerSmooth=1.0 \
--InCol DATA \
--Weighting Natural \
--UVMinMax=0.100000,1000.000000 \
--SolsDir=SOLSDIRjosh  \
--BeamMode LOFAR \
--LOFARBeamMode=A --DDFCacheDir=. \
--NodesFile image_dirin_SSD_m.npy.ClusterCat.npy \
--DicoModel image_full_ampphase_di_m.NS.DicoModel
```

## Upon inspecting the killMS.DDjosh.sols.npz
These are the available keys to the numpy file,
``` python
['ModelName', 'FreqDomains', 'StationNames', 'BeamTimes', 'SourceCatSub', 'ClusterCat', 'Sols', 'SkyModel']
```

The `FreqDomains` is,
``` python
[[1.20213318e+08 1.21189880e+08]
 [1.21189880e+08 1.22166443e+08]]
```

`BeamTimes` is an array of 96 mjs times.

`SkyModel` is 45 rows of things like:
('', 2.21188814, 1.17948525,  0.00329686,  0.05361011,  4.5654546 , 0)
I'm guessing:
Name, RA,      , DEC,      Not sure about last 4.

`Sols` is 3600 entries (one per time step of the obs) of tuples of length 4:
Each tuple is:
(start time, end time, array of shape (2, 62, 45, 2, 2), array of shape (2, 62, 4))

It's very confusing and and not the best way to structure things for sure.

## What I'd like to get
``` python
directions : float array (Nd, 2) RA and DEC of facets
stations : str array (Na, 1) Station names
times : float array (Nt, 2) start and end times of each timestamp in mjd*86400
freqs : float array (Nf, 2) start and end freqs of each freq chunk
gains : complex array (Na, Nt, Nd, Nf, Npol, 1) the gains
OR
amplitude : float array (Na, Nt, Nd, Nf, Npol, 1) the amplitude
phase : float array (Na, Nt, Nd, Nf, Npol, 1) the phase
Where
Na : num antenna
Nt : num timesteps
Nd : num directions
Nf : num freq chunks
Npol : num polarizations
```

**Comment by Joshuaalbert** [comment]
Also, you can get the example file at 
`/disks/ftphome/pub/albert/killMS.example.sols.npz`

**Comment by rvweeren** [comment]
Problem is that killMS2H5parm.py is looks for TEC, not all kMS solutions have that. Some have only Gains.

**Comment by Joshuaalbert** [comment]
#52 solves this
