### ISSUE TITLE
POLALIGN crash

### ISSUE THREAD

**Issue by adrabent** [revoltek/losoto#83]
In the current prefactor I encounter a crash at the PA steps:

```
2019-02-20 15:49:13 - INFO: --> Starting 'align' step (operation: POLALIGN).
2019-02-20 15:49:13 - INFO: Finding polarization align for soltab: phase000
2019-02-20 15:49:13 - INFO: Creating a new solution-table: polalign. 
Traceback (most recent call last):        
  File "/home/drabent/losoto/bin/losoto", line 147, in <module>
    returncode += ops[ op ]._run_parser( soltab, parser, step )
  File "/home/drabent/losoto/losoto/operations/polalign.py", line 18, in _run_parser
    return run(soltab, soltabOut, maxResidual, fitOffset, average, replace, refAnt)
  File "/home/drabent/losoto/losoto/operations/polalign.py", line 81, in run
    for vals, weights, coord, selection in soltab.getValuesIter(returnAxes=['freq','pol','time'], weight=True, reference=refAnt):
  File "/home/drabent/losoto/losoto/h5parm.py", line 1276, in getValuesIter
    if weight: weigthVals = self.getValues(retAxesVals=False, weight=True, reference=reference)
  File "/home/drabent/losoto/losoto/h5parm.py", line 1223, in getValues
    dataVals[ dataValsRef == 0. ] = 0.
IndexError: boolean index did not match indexed array along dimension 0; dimension is 60 but corresponding boolean dimension is 1
```

I can reproduce this error with the following parset:
```
[align]
fitOffset = False
average = True
replace = True
soltab = sol000/phase000
soltabOut = polalign
operation = POLALIGN
refAnt = closest
```

These are the solutions plotted from `sol000/phase000`:
![polalign_ph_polxx](https://user-images.githubusercontent.com/19146990/53106325-1432f980-3533-11e9-9058-dbc234f8e7e2.png)
Thus input data looks fine.

**Comment by revoltek** [comment]
is this problem still present?
