### ISSUE TITLE
tec without jumps detected, yet still continues

### ISSUE THREAD

**Issue by tikk3r** [revoltek/losoto#95]
I'm trying the TECJUMP on some long baseline HBA tec solutions in different directions (which are separate h5parms), but I'm seeing a strange occurence where on two h5parms the code does not find any jumps, but still tries to "dejump" it. The other 44 run fine. It happens in these lines:
https://github.com/revoltek/losoto/blob/727df32392e4d16d78fd6c608486fedc5f9667d7/losoto/operations/tecjump.py#L305-L316
I'm running with the following parset:
```
[dejump]
operation = TECJUMP
refAnt = RS106HBA
soltab = sol000/tec000
```
Running `losoto <h5parm> <parset>` crashes with
```
2019-08-15 14:09:11 - INFO: --> Starting 'dejump' step (operation: TECJUMP).
2019-08-15 14:09:11 - INFO: Removing TEC jumps from soltab: tec000
/net/lofar1/data1/sweijen/software/LOFAR/lofarenv/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:1076: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
2019-08-15 14:09:11 - INFO: TEC jump - theoretical: 0.03141 TECU - estimated: nan TECU
2019-08-15 14:09:12 - INFO: Working on ant: RS106HBA
/net/lofar1/data1/sweijen/software/LOFAR/2019_04_04/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/losoto/operations/tecjump.py:327: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  vals_e = np.squeeze(vals_e_all[selection])
```
Running the same snipped in a shell, on the same h5, however, gives this:
```python
In [1]: import losoto.h5parm as h5p
imp
In [2]: import numpy as np

In [3]: h5 = h5p.h5parm('phaseonlyP280.mssolsgrid_2.h5')

In [4]: ss = h5.getSolset('sol000')

In [5]: soltab = ss.getSoltab('tec000')

In [6]: import logging

In [7]: tec_jump_theory = 0.03141

In [12]:     # Find the average jump on all antennas by averaging all jumps found to be withing 0.5 and 2 times the tec_jump_theory
    ...:     vals = soltab.getValues( retAxesVals=False, reference=refAnt )
    ...:     timeAxis = soltab.getAxesNames().index('time')
    ...:     vals = np.swapaxes(vals, 0, timeAxis)
    ...:     vals = vals[1,...] - vals[:-1,...] 
    ...:     vals = vals[(vals > tec_jump_theory*1) & (vals < tec_jump_theory*1.5)]
    ...:     if len(vals) == 0: 
    ...:         logging.info('TEC jump - theoretical: %.5f TECU - NO JUMP FOUND' % (tec_jump_theory))
    ...:         print('return 0')
    ...:     tec_jump = np.nanmedian(vals)
    ...: 
    ...: logging.info('TEC jump - theoretical: %.5f TECU - estimated: %.5f TECU' % (tec_jump_theory, tec_jump))
    ...: 
2019-08-15 14:17:01 - INFO: TEC jump - theoretical: 0.03141 TECU - NO JUMP FOUND
return 0 # Function would've exited here.
2019-08-15 14:17:01 - INFO: TEC jump - theoretical: 0.03141 TECU - estimated: nan TECU
```

I don't see why only these two directions would slip through.

**Comment by revoltek** [comment]
Consider that the TECJUMP is highly experimental :)
does the problem happens on the reference station? I think the best is to look inside the vals array once the search for the jumps has happened.

**Comment by tikk3r** [comment]
The reference station isn't mentioned in the output. It seems to work for RS205, but all other stations crash:
```
(lofarenv) sweijen@lofar6:/data2/sweijen/merge_directions_for_ddf/44dirs> losoto phaseonlyP280.mssolsgrid_2.h5 losoto_dejump_tec.parset
2019-08-15 14:45:33 - INFO: --> Starting 'dejump' step (operation: TECJUMP).
2019-08-15 14:45:33 - INFO: Removing TEC jumps from soltab: tec000
/net/lofar1/data1/sweijen/software/LOFAR/lofarenv/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:1076: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
2019-08-15 14:45:33 - INFO: TEC jump - theoretical: 0.03141 TECU - estimated: nan TECU
2019-08-15 14:45:33 - INFO: Working on ant: RS205HBA
/net/lofar1/data1/sweijen/software/LOFAR/2019_04_04/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/losoto/operations/tecjump.py:327: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  vals_e = np.squeeze(vals_e_all[selection])
2019-08-15 14:45:33 - INFO: Working on ant: RS208HBA
/net/lofar1/data1/sweijen/software/LOFAR/2019_04_04/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/losoto/operations/tecjump.py:166: RuntimeWarning: invalid value encountered in greater
  jumps_idx = np.where(np.abs(vals_diff) > tec_jump*(2/3.))[0] # find jumps
Process multiThread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/net/lofar1/data1/sweijen/software/LOFAR/2019_04_04/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/losoto/lib_operations.py", line 35, in run
    self.funct(*parms, outQueue=self.outQueue)
.
.
<same error for all other stations>
```

After it searched for jumps, vals is empty:
```python
In [34]: vals = vals[(vals > tec_jump_theory*1) & (vals < tec_jump_theory*1.5)]

In [35]: vals.shape
Out[35]: (0,)

In [36]: len(vals)
Out[36]: 0
```

**Comment by revoltek** [comment]
hum, I see the problem... it seems more a coding bug rather than a conceptual issue. If you cannot find a solution you can send me the h5parm and I'll look at it (but I am quite busy now, it can take some time)

**Comment by tikk3r** [comment]
Sure, take your time. I've attached the h5parm (gzipped).
[phaseonlyP280.mssolsgrid_2.h5.gz](https://github.com/revoltek/losoto/files/3545462/phaseonlyP280.mssolsgrid_2.h5.gz)
