### ISSUE TITLE
Compatibility with Python 3

### ISSUE THREAD

**Issue by flomertens** [revoltek/losoto#99]
Running the following command with latest git losoto on python 3.7.5:

`losoto instrument.h5 losoto_plot_sols.parset `

I got the following error:

```
Traceback (most recent call last):
  File "/home/users/mertens/soft/conda3/bin/losoto", line 98, in <module>
    import losoto.operations as operations
  File "/home/users/mertens/soft/conda3/lib/python3.7/site-packages/losoto/operations/__init__.py", line 6, in <module>
    __import__(x, locals(), globals())
ModuleNotFoundError: No module named '__init__'`
```

I presume this is because of the limitations of relative imports in python 3.

**Comment by revoltek** [comment]
I think this has been fixed, let me know if not
